class AddStuffToProfiles < ActiveRecord::Migration
  def change
    add_column :profiles, :beach, :string
    add_column :profiles, :peanut_jelly, :string
    add_column :profiles, :animal_boys, :string
    add_column :profiles, :fireman_spaceman, :string
    add_column :profiles, :games_sports, :string
    add_column :profiles, :seitan_satan, :string
    add_column :profiles, :one_fish, :string
    add_column :profiles, :sixnine_fourtwenty, :string
    add_column :profiles, :mint_ice, :string
    add_column :profiles, :marriage_divorce, :string
    add_column :profiles, :steve_jane, :string
    add_column :profiles, :marco_polo, :string
    add_column :profiles, :where_who, :string
    add_column :profiles, :mfa_mba, :string
    add_column :profiles, :soup_salad, :string
    add_column :profiles, :paper_plastic, :string
    add_column :profiles, :cut_uncut, :string
    add_column :profiles, :summer_wrestle, :string
    add_column :profiles, :bush_clinton, :string
    add_column :profiles, :perot_buchanan, :string
    add_column :profiles, :pizza_taco, :string
    add_column :profiles, :molly_lucy, :string
    add_column :profiles, :energy, :string
    add_column :profiles, :pitcher_tallboy, :string
    add_column :profiles, :shirts_skins, :string
    add_column :profiles, :spark_tap, :string
    add_column :profiles, :rap_metal, :string
    add_column :profiles, :brush_floss, :string
    add_column :profiles, :vinyl_flac, :string
    add_column :profiles, :yes_no, :string
    add_column :profiles, :hbo_Sho, :string
    add_column :profiles, :privelage, :string
    add_column :profiles, :business_pleasure, :string
    add_column :profiles, :liquor_before, :string
    add_column :profiles, :sunrise_set, :string
    add_column :profiles, :hall_oates, :string
    add_column :profiles, :simon_garfunkle, :string
    add_column :profiles, :beatles, :string
    add_column :profiles, :stick_tribal, :string
    add_column :profiles, :nor_so, :string
    add_column :profiles, :gluten_mumia, :string
    add_column :profiles, :mac_pc, :string
    add_column :profiles, :netflix_chill, :string
    add_column :profiles, :fat_jerry, :string
    add_column :profiles, :friends_benefit, :string
    add_column :profiles, :duck_goose, :string
    add_column :profiles, :black_monday, :string
    add_column :profiles, :eeny_meeny, :string
    add_column :profiles, :chicken_egg, :string
    add_column :profiles, :calvin_hobbes, :string
  end
end
