class AddMoreQuestionsToProfiles < ActiveRecord::Migration
  def change
    add_column :profiles, :peaches_herb, :string
    add_column :profiles, :juggalo_bungalow, :string
    add_column :profiles, :pecan_duncan, :string
    add_column :profiles, :gummy_sandals, :string
    add_column :profiles, :fela_bela, :string
    add_column :profiles, :eggo_ego, :string
    add_column :profiles, :seger_dylan, :string
    add_column :profiles, :kleenex_skrillex, :string
    add_column :profiles, :smoke_bowls, :string
    add_column :profiles, :webbed_nipple, :string
    add_column :profiles, :zoobilee_riot, :string
    add_column :profiles, :have_hold, :string
    add_column :profiles, :mandles, :string
    add_column :profiles, :rat_duck, :string
    add_column :profiles, :mandatory_overdrive, :string
    add_column :profiles, :townhouse_zandt, :string
    add_column :profiles, :jedi_jew, :string
    add_column :profiles, :lydia_lunchables, :string
    add_column :profiles, :appeteaser, :string
    add_column :profiles, :opp_dna, :string
    add_column :profiles, :pauly_cole, :string
    add_column :profiles, :deuce_man, :string
    add_column :profiles, :paul_report, :string
    add_column :profiles, :lmfao_schwarts, :string
    add_column :profiles, :blind_massacre, :string
    add_column :profiles, :ebola_ricola, :string
    add_column :profiles, :march_martha, :string
    add_column :profiles, :mocha_flat, :string
    add_column :profiles, :sousa_siouxsie, :string
    add_column :profiles, :ovaltine_carnation, :string
    add_column :profiles, :bad_high, :string
    add_column :profiles, :stop_by, :string
    add_column :profiles, :feminism_euphemism, :string
    add_column :profiles, :bf_lynnard, :string
    add_column :profiles, :loch_quik, :string
    add_column :profiles, :warby_pork, :string
    add_column :profiles, :canned_liquid, :string
    add_column :profiles, :purina_purell, :string
    add_column :profiles, :hook_crook, :string
    add_column :profiles, :heart_eurythmics, :string
    add_column :profiles, :would_rather, :string
    add_column :profiles, :tar_feather, :string
    add_column :profiles, :dead_alive, :string
    add_column :profiles, :time_meaning, :string
    add_column :profiles, :bicuspid_molar, :string
    add_column :profiles, :fame_riches, :string
    add_column :profiles, :right_wrong, :string
    add_column :profiles, :quantum_determinism, :string
    add_column :profiles, :type_hep, :string
    add_column :profiles, :b_a, :string
    add_column :profiles, :ants_aunts, :string
    add_column :profiles, :llama_alpaca, :string
    add_column :profiles, :pretty_shitty, :string
    add_column :profiles, :gw_dubstep, :string
    add_column :profiles, :cornithians_thessalonians, :string
    add_column :profiles, :pea_coat, :string
    add_column :profiles, :spy_kids, :string
    add_column :profiles, :cronut_dossant, :string
    add_column :profiles, :some_none, :string
    add_column :profiles, :bad_back, :string
    add_column :profiles, :lotto, :string
    add_column :profiles, :williams_bush, :string
    add_column :profiles, :win_lose, :string
    add_column :profiles, :dragons_lizards, :string
    add_column :profiles, :werewolves_vampires, :string
    add_column :profiles, :regular_pot, :string
    add_column :profiles, :anime_manga, :string
    add_column :profiles, :advice_dice, :string
    add_column :profiles, :alice_wonderchain, :string
    add_column :profiles, :swiss_rainbow, :string
    add_column :profiles, :found, :string
    add_column :profiles, :alpha_omega, :string
    add_column :profiles, :ship_toads, :string
    add_column :profiles, :pleistoscene_pleiades, :string
    add_column :profiles, :money_clicks, :string
    add_column :profiles, :grave_tomb, :string
    add_column :profiles, :october_mischief, :string
    add_column :profiles, :choke_nelson, :string
    add_column :profiles, :blue_stripe, :string
    add_column :profiles, :war_peace, :string
    add_column :profiles, :scarlet_plum, :string
    add_column :profiles, :reynolds_gosling, :string
    add_column :profiles, :erudite_airy, :string
    add_column :profiles, :hey_hay, :string
    add_column :profiles, :nay_neigh, :string
    add_column :profiles, :omg_lol, :string
    add_column :profiles, :pay_pal, :string
    add_column :profiles, :toilet, :string
    add_column :profiles, :olsen_twins, :string
    add_column :profiles, :hot_not, :string
    add_column :profiles, :demon_daemon, :string
    add_column :profiles, :crumple_rumple, :string
    add_column :profiles, :tractor, :string
    add_column :profiles, :home_peter, :string
    add_column :profiles, :work, :string
    add_column :profiles, :collaborate_corroborate, :string
    add_column :profiles, :eb_white, :string
    add_column :profiles, :hat, :string
    add_column :profiles, :this_that, :string
    add_column :profiles, :cancer_heart, :string
    add_column :profiles, :stuff_things, :string
    add_column :profiles, :permission_forgiveness, :string
    add_column :profiles, :capitalism_equality, :string
  end
end
